version: "3.9"

services:
  redis:
    image: redis:7
    container_name: feast_redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow

    container_name: mlflow_server
    ports:
      - "5001:5001"
    volumes:
      - mlruns_data:/mlruns
      - mlflow_db:/mlflow.db
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 5001
      --allowed-hosts "*"
    restart: always


  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mlflow
    environment:
      - REDIS_HOST=redis
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    volumes:
      - .:/app
      - dvc_cache:/app/.dvc/cache
    restart: always

volumes:
  redis_data:
  mlruns_data:
  mlflow_db:
  dvc_cache: